config/routes.rb
PatternGuess::Application.routes.draw do
  resources :patterns

  root 'patterns#index'

  

end

app/models/pattern.rb
class Pattern < ActiveRecord::Base
  EMPTY_PATTERN = [
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
  ]

  serialize :content
  serialize :guess_state

  after_initialize :init_patterns

  private
    def init_patterns
      self.content      ||= EMPTY_PATTERN
      self.guess_state  ||= EMPTY_PATTERN
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  before_action :set_pattern, only: [:show, :edit, :update, :destroy]

  # GET /patterns
  # GET /patterns.json
  def index
    @patterns = Pattern.all
  end

  # GET /patterns/1
  # GET /patterns/1.json
  def show
  end

  # GET /patterns/new
  def new
    @pattern = Pattern.new
  end

  # GET /patterns/1/edit
  def edit
  end

  # POST /patterns
  # POST /patterns.json
  def create
    @pattern = Pattern.new(pattern_params)

    respond_to do |format|
      if @pattern.save
        format.html { redirect_to edit_pattern_path(@pattern), notice: 'Pattern was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pattern }
      else
        format.html { render action: 'new' }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patterns/1
  # PATCH/PUT /patterns/1.json
  def update
    respond_to do |format|
      if @pattern.update(pattern_params)
        format.html { redirect_to @pattern, notice: 'Pattern was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patterns/1
  # DELETE /patterns/1.json
  def destroy
    @pattern.destroy
    respond_to do |format|
      format.html { redirect_to patterns_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pattern
      @pattern = Pattern.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pattern_params
      out_params = params.require(:pattern).permit!

      if params[:action] == 'create'
        out_params = {}
      else
        [:content, :guess_state].each do |attr_name|
          out_params[attr_name] = params[:pattern][attr_name].map do |row|
            row.map(&:to_i)
          end if params[:pattern][attr_name]
        end
      end

      out_params
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="pattern-guess">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Pattern Guess</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="/assets/javascripts/html5shiv.js"></script>
      <script src="/assets/javascripts/js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <div class="page-header">
        <h1>Patterns!</h1>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/patterns/_form.html.erb
<div ng-controller="PatternFieldController">
  <%= form_for(@pattern) do |f| %>
    <% if @pattern.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@pattern.errors.count, "error") %> prohibited this pattern from being saved:</h2>

        <ul>
        <% @pattern.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <b>Content</b>
    <p>
      <small>
        Your changes are saved automatically as you change the pattern.
      </small>
    </p>
    <div class="pattern-container pattern-container-big">

      <input  type="hidden"
              ng-model="patternId"
              ng-init="patternId=<%= @pattern.id || 0 %>"
              id="pattern-id"
              value="<%= @pattern.id || 0 %>"
      />

      <div ng-repeat="line in content">
        <div class="pattern-row">
          <div class="pattern-cell pattern-cell-{{cellClassState(cell)}}"
              ng-repeat="cell in line"
              ng-click="toggleCell($parent.$index, $index)" >
            &nbsp;
          </div>
        </div>
        <br style="clear: both"/>
      </div>
    </div>

  <% end %>

</div>

app/views/patterns/_pattern_preview.html.erb
<% pattern_content.each do |row| %>
  <div class="pattern-row">
    <% row.each do |cell| %>
      <div class="pattern-cell pattern-cell-<%= cell == 1 ? :active : :inactive %>">
        &nbsp;
      </div>
    <% end %>
  </div>
  <div class="clearfix"></div>
<% end %>

app/views/patterns/edit.html.erb
<h2>Editing pattern</h2>

<%= render 'form' %>

<br class="clearfix" />

<div class="btn-group">
  <%= link_to 'Listing', patterns_path, class: 'btn btn-default' %>
  <%= link_to 'Show', @pattern, class: 'btn btn-primary' %>
</div>

<br class="clearfix" />

app/views/patterns/index.html.erb
<h2>Listing patterns</h2>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Content</th>
      <th>Guess state</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @patterns.each do |pattern| %>
      <tr>
        <td>
          <%= link_to edit_pattern_path(pattern), title: 'Edit pattern' do %>
            <div class="pattern-container pattern-container-small">
              <%= render partial: 'patterns/pattern_preview',
                         locals: {pattern_content: pattern.content} %>
            </div>
          <% end %>
        </td>
        <td>
          <%= link_to pattern_path(pattern), title: 'Edit guess for pattern' do %>
            <div class="pattern-container pattern-container-small">
              <%= render partial: 'patterns/pattern_preview',
                         locals: {pattern_content: pattern.guess_state} %>
            </div>
          <% end %>
        </td>
        <td>
          <%= link_to 'Destroy', @pattern,  class: 'btn btn-danger',
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pattern', url_for(action: :create, pattern: {create: :auto}), method: :post %>

app/views/patterns/new.html.erb
<h1>New pattern</h1>

<%= render 'form' %>

<%= link_to 'Back', patterns_path %>

app/views/patterns/show.html.erb
<h2>Show – Let's guess the pattern</h2>

<% action_nav = capture do %>
<br class="clearfix" />

<div class="btn-group">
  <%= link_to 'Listing', patterns_path, class: 'btn btn-default' %>
  <%= link_to 'Edit', edit_pattern_path(@pattern), class: 'btn btn-primary' %>
  <%= link_to 'Destroy', @pattern,  class: 'btn btn-danger',
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</div>

<br class="clearfix" />
<% end %>

<%= action_nav %>

<p id="notice"><%= notice %></p>

<div>
  <strong>Content:</strong>
  <small class="text-left">Just for reference. IMMUTABLE. </small>
  <div class="pattern-container pattern-container-big">
    <%= render partial: 'patterns/pattern_preview',
               locals: {pattern_content: @pattern.content} %>
  </div>
</div>

<div>
  <strong>Guess state:</strong>
  <div ng-controller="PatternGuessController">
    <div class="pattern-container pattern-container-big">

      <input  type="hidden"
              ng-model="patternId"
              ng-init="patternId=<%= @pattern.id %>"
              id="pattern-id"
              value="<%= @pattern.id %>"
      />

      <div ng-repeat="line in guessState">
        <div class="pattern-row">
          <div class="pattern-cell pattern-cell-{{cellClassState(cell)}}"
              ng-repeat="cell in line"
              ng-click="toggleCell($parent.$index, $index)" >
            &nbsp;
          </div>
        </div>
        <br style="clear: both"/>
      </div>
    </div>
  </div>
</div>

<div class="modal face" id="successModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Successful step!</h4>
      </div>
      <div class="modal-body">
        You've just matched the original pattern.
        Let's <%= link_to 'create new pattern',
                          url_for(  action: :create,
                                    pattern: {create: :auto}
                          ),
                          method: :post %>
      </div>
    </div>
  </div>
</div>

<%= action_nav %>